---
- name: Setting up docker nodes
  hosts: linux1
  become: yes

  tasks:

  - block: #--------Ubuntu linux-------
      - name: Before Istall docker on Ubuntu
        apt:
          name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
          state: latest
          update_cache: yes
      - name: GPG key download
        get_url:
          url: https://download.docker.com/linux/ubuntu/gpg
          dest: /tmp/docker.gpg
        notify:
          - GPT key add
      - name: Add repo
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu disco stable
          state: present
#         ignore_errors: yes
      - name: Istall docker on Ubuntu
        apt:
          name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
          state: latest

    when: ansible_os_family == "Debian"
           #--------Ubuntu linux-------
  
  - name: Run docker
    shell: docker


  handlers:
  - name: GPT key add
    shell: apt-key add /tmp/docker.gpg && apt-key fingerprint 0EBFCD88
